pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                chackout scm
            }
        }
        stage('terraform') {
            steps {
                sh'./terraform init'
            }
        }
    }
}

